spring.application.name=backend

server.port=9999

spring.datasource.url=jdbc:mysql://localhost:3306/pruebaballon
spring.datasource.username=usuario
spring.datasource.password=usuario
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect

#Validacion
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Seguridad JWT
jwt.secret=Mzk4YThjMTY5ZDM4OTU2MzhlMDQ2OGNmYjVkNDI3M2NjMWRmZjg3YTAyYmRhMTg0YjlmZDE1MzYyYjU2YjUzYg==
jwt.expiration-ms=3600000

# === Envio de correos via Gmail ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#Para desplegar la app hay que proporcionar estas dos variables de entorno
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Remitente que vera el usuario en su bandeja de entrada
ballon.mail.from=${MAIL_USERNAME}
ballon.mail.from-name=Ball-On